# Generated by Django 5.0.7 on 2024-07-17 04:10

import isbn_field.fields
import isbn_field.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_cover_book_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=isbn_field.fields.ISBNField(blank=True, max_length=28, null=True, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN'),
        ),
    ]
